### ISSUE TITLE
Cannot install because permissions denied

### ISSUE THREAD

**Issue by akoval** [ForbesLindesay/spawn-sync#14] opened 2015-04-20 12:52 UTC
```
> spawn-sync@1.0.6 postinstall /project/node_modules/spawn-sync
> node postinstall


fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied 'project/node_modules/spawn-sync/package.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at Object.<anonymous> (/project/node_modules/spawn-sync/postinstall.js:33:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "spawn-sync"
npm ERR! node v0.10.37
npm ERR! npm  v2.8.3
npm ERR! code ELIFECYCLE

```

I installed with ```--ignore-scripts``` and see that this file (package.json) has root as owner. So my user cannot write to file in your postinstall script

**Comment by leobalter** [comment] 2015-04-20 13:57
duplicate of #11

**Closed by leobalter** 2015-04-20 13:57 UTC

**Comment by ForbesLindesay** [comment] 2015-07-16 17:02
The latest version should fix this problem.
